
# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/todo
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

# Allow Thymeleaf templates to be reloaded without restarting the application
spring.thymeleaf.cache=false
